### ISSUE TITLE
KeyError of spacy and how do i run the codes on the other two datasets.

### ISSUE THREAD

**Issue by Lee-zix** [mickeystroller/ETypeClus#3]
1.  When i run the command "python3 parse_corpus_and_extract_svo.py \
    --is_sentence 1 \
    --input_file ./covid19/corpus.txt \
    --save_path ./covid19/corpus_parsed_svo.pk",
I see errors:

 print(tok, tok.pos_, tok.dep_)
  File "token.pyx", line 864, in spacy.tokens.token.Token.pos_.__get__
KeyError: 84
 
It seems that spacy has some bugs to get the pos of the word "false" when parsing the sentence "Institut Pasteur warns against false information circulating on social media". Could you give some suggestions? 

2. How do I run the code on the ACE and ERE datasets??

**Comment by Lee-zix** [comment]
The first question has been solved when I upgraded the version of spacy to V3.0. Maybe the version of spacy in the  requirement.txt could be updated?? And how about the second question?

**Comment by mickeysjm** [comment]
For the second question, due to the license issue, we can not directly release the ACE and ERE datasets. However, you can download them from the official website and preprocess them into the same format as the example covid19 and pandemic datasets in [https://drive.google.com/drive/folders/1_QVv9XwN6PjZGdeMJWqW5D75NJmaD6F1?usp=sharing](https://drive.google.com/drive/folders/1-oqDLwlt94dFqAYDh6hhIbjt852_qCm7?usp=sharing).
